repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-yaml
        exclude: "mkdocs.yml"
      - id: end-of-file-fixer
      - id: trailing-whitespace
