markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.extra
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
#  - toc:
#      toc_depth : "1-1"
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg ''
      emoji_index: !!python/name:material.extensions.emoji.twemoji ''
  - pymdownx.superfences:
      custom_fences:
        - class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ''
          name: mermaid
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - search
  - table-reader
  - glightbox
  - blog:
#      blog_toc: true
#      post_url_date_format: yyyy
#repo_name: foutoucour/les-paul-classics
#repo_url: https://github.com/foutoucour/les-paul-classics
site_description: Gibson Les Paul Classic models
site_name: Les Paul Classic Pedia
site_url: https://lespaulclassicpedia.com
theme:
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github
  name: material
  custom_dir: overrides
  palette:
    - accent: deep-orange
      primary: black
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - accent: deep-orange
      primary: black
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  analytics:
    provider: google
    property: G-4KRZ9089EN
nav:
  - index.md
#  - Models:
#    - models/index.md
#    - blog/posts/2007-les-paul-classic-antique.md
#    - blog/posts/2007-les-paul-classic-custom.md
  - Blog:
    - blog/index.md
  - resources.md


