guitars = {
    "gibson-les-paul-classic-vintage-1993-japan-yamano-price-drop": {
        "url": "https://reverb.com/ca/item/71693844-gibson-les-paul-classic-vintage-1993-japan-yamano-ink-stamped-heritage-cherry-beautifully-aged-w-yamano-booklet-ohsc",
        "name": "Gibson Les Paul Classic Vintage 1993 Japan Yamano Ink Stamped Heritage Cherry Beautifully Aged w/ Yamano Booklet & OHSC",
        "slug": "gibson-les-paul-classic-vintage-1993-japan-yamano-ink-stamped-heritage-cherry-beautifully-aged-w-yamano-booklet-ohsc",
        "location": "Salt Lake City, UT, United States",
        "image": "https://rvb-img.reverb.com/image/upload/s--_FJsW8Ju--/a_0,c_crop,h_0.752,w_1.000,x_0.000,y_0.140/f_auto,t_supersize/v1699836373/rvyu6j6lho3fogbrghme.jpg",
        "model": {
            "name": "Les Paul Classic",
            "image": "https://rvb-img.reverb.com/image/upload/s--RTvu8k1C--/t_card-square/v1569617910/bwomejvvavofqevhcb7b.jpg",
            "slug": "les-paul-classic",
            "status": "Want",
            "year": {"year": "1990 - 2011", "start": 1990, "end": 2011},
            "finishes": [
                "Amber",
                "Bullion Gold",
                "Ebony",
                "Heritage Cherry Sunburst",
                "Honey Burst",
                "Lightburst",
            ],
            "url": "https://reverb.com/ca/p/gibson-les-paul-classic-electric-guitar",
            "price_guide": {
                "low_bracket": 1940,
                "high_bracket": 2849,
            },
        },
        "previous_price": 4000,
        "discount": None,
        "price": 3499,
        "shipping_price": 194,
        "accept_offers": True,
        "watched": True,
        "status": "Available",
    },
    "gibson-les-paul-classic-vintage-1993-japan-yamano-good-deal": {
        "url": "https://reverb.com/ca/item/71693844-gibson-les-paul-classic-vintage-1993-japan-yamano-ink-stamped-heritage-cherry-beautifully-aged-w-yamano-booklet-ohsc",
        "name": "Gibson Les Paul Classic Vintage 1993 Japan Yamano Ink Stamped Heritage Cherry Beautifully Aged w/ Yamano Booklet & OHSC",
        "slug": "gibson-les-paul-classic-vintage-1993-japan-yamano-ink-stamped-heritage-cherry-beautifully-aged-w-yamano-booklet-ohsc",
        "location": "Salt Lake City, UT, United States",
        "image": "https://rvb-img.reverb.com/image/upload/s--_FJsW8Ju--/a_0,c_crop,h_0.752,w_1.000,x_0.000,y_0.140/f_auto,t_supersize/v1699836373/rvyu6j6lho3fogbrghme.jpg",
        "model": {
            "image": "https://rvb-img.reverb.com/image/upload/s--RTvu8k1C--/t_card-square/v1569617910/bwomejvvavofqevhcb7b.jpg",
            "name": "Les Paul Classic",
            "slug": "les-paul-classic",
            "status": "Want",
            "year": {"year": "1990 - 2011", "start": 1990, "end": 2011},
            "finishes": [
                "Amber",
                "Bullion Gold",
                "Ebony",
                "Heritage Cherry Sunburst",
                "Honey Burst",
                "Lightburst",
            ],
            "url": "https://reverb.com/ca/p/gibson-les-paul-classic-electric-guitar",
            "price_guide": {
                "low_bracket": 1940,
                "high_bracket": 4000,
            },
        },
        "previous_price": None,
        "discount": None,
        "price": 3499,
        "shipping_price": 194,
        "accept_offers": True,
        "watched": True,
        "status": "Available",
    },
    "gibson-les-paul-classic-vintage-1993-japan-yamano": {
        "url": "https://reverb.com/ca/item/71693844-gibson-les-paul-classic-vintage-1993-japan-yamano-ink-stamped-heritage-cherry-beautifully-aged-w-yamano-booklet-ohsc",
        "name": "Gibson Les Paul Classic Vintage 1993 Japan Yamano Ink Stamped Heritage Cherry Beautifully Aged w/ Yamano Booklet & OHSC",
        "slug": "gibson-les-paul-classic-vintage-1993-japan-yamano-ink-stamped-heritage-cherry-beautifully-aged-w-yamano-booklet-ohsc",
        "location": "Salt Lake City, UT, United States",
        "image": "https://rvb-img.reverb.com/image/upload/s--_FJsW8Ju--/a_0,c_crop,h_0.752,w_1.000,x_0.000,y_0.140/f_auto,t_supersize/v1699836373/rvyu6j6lho3fogbrghme.jpg",
        "model": {
            "image": "https://rvb-img.reverb.com/image/upload/s--RTvu8k1C--/t_card-square/v1569617910/bwomejvvavofqevhcb7b.jpg",
            "name": "Les Paul Classic",
            "slug": "les-paul-classic",
            "status": "Want",
            "year": {"year": "1990 - 2011", "start": 1990, "end": 2011},
            "finishes": [
                "Amber",
                "Bullion Gold",
                "Ebony",
                "Heritage Cherry Sunburst",
                "Honey Burst",
                "Lightburst",
            ],
            "url": "https://reverb.com/ca/p/gibson-les-paul-classic-electric-guitar",
            "price_guide": {
                "low_bracket": 1940,
                "high_bracket": 2849,
            },
        },
        "previous_price": None,
        "discount": None,
        "price": 3499,
        "shipping_price": 194,
        "accept_offers": True,
        "watched": True,
        "status": "Available",
    },
    "gibson-1994-les-paul-classic-plemium-plus": {
        "url": "https://reverb.com/ca/item/75833549-gibson-1994-les-paul-classic-plemium-plus?show_sold=true",
        "name": "Gibson 1994 Les Paul Classic Plemium Plus",
        "slug": "gibson-1994-les-paul-classic-plemium-plus",
        "location": "Salt Lake City, UT, United States",
        "image": "https://rvb-img.reverb.com/image/upload/s--_FJsW8Ju--/a_0,c_crop,h_0.752,w_1.000,x_0.000,y_0.140/f_auto,t_supersize/v1699836373/rvyu6j6lho3fogbrghme.jpg",
        "model": None,
        "previous_price": None,
        "discount": None,
        "price": 3188,
        "shipping_price": 249,
        "accept_offers": False,
        "watched": True,
        "status": "Ended",
    },
    "2003-gibson-les-paul-classic-triple-humbucker-electric-guitar-w-ohsc": {
        "url": "https://reverb.com/ca/item/75854927-2003-gibson-les-paul-classic-triple-humbucker-electric-guitar-w-ohsc?show_sold=true",
        "name": "2003 Gibson Les Paul Classic Triple Humbucker Electric Guitar w/ OHSC",
        "slug": "2003-gibson-les-paul-classic-triple-humbucker-electric-guitar-w-ohsc",
        "location": "Salt Lake City, UT, United States",
        "image": "https://rvb-img.reverb.com/image/upload/s--_FJsW8Ju--/a_0,c_crop,h_0.752,w_1.000,x_0.000,y_0.140/f_auto,t_supersize/v1699836373/rvyu6j6lho3fogbrghme.jpg",
        "model": {
            "name": "Les Paul Classic 3 Pickups",
            "image": "https://rvb-img.reverb.com/image/upload/s--RTvu8k1C--/t_card-square/v1569617910/bwomejvvavofqevhcb7b.jpg",
            "slug": "les-paul-classic-3-pickups",
            "status": "Want",
            "year": {"year": "1994", "start": 1994, "end": 1994},
            "finishes": [],
            "url": "https://reverb.com",
            "price_guide": None,
        },
        "previous_price": None,
        "discount": None,
        "price": 3344,
        "shipping_price": 213,
        "accept_offers": False,
        "watched": True,
        "status": "Sold",
    },
}
